### ISSUE TITLE
VOLTE NOT WORKING AFTER UPDATE 1.24

### ISSUE THREAD

**Issue by SCiZOR16** [kyujin-cho/pixel-volte-patch#104]
The VOLTE is supposed to work but after the update, it isn't work on my pixel 7

**Comment by kyujin-cho** [comment]
Thanks for the report. Did you confirm that VoLTE is working fine when using version 1.2.2?

**Comment by SCiZOR16** [comment]
I never tried 1.2.2 as i directly installed 1.2.4..!!
But there popped a option for 4G Calling in my SIM section after doing the process but when i do the *#*#4636#*#* i dont see IMS Registered

Below is the attached images of both
![Screenshot_20230404-024900](https://user-images.githubusercontent.com/129538276/229599803-cdfc6051-d3af-4a1d-9886-3f94e62d43e4.png)
![Screenshot_20230404-024705](https://user-images.githubusercontent.com/129538276/229599814-7e138cab-701a-4465-8b32-8de9d5a82f82.png)

**Comment by kyujin-cho** [comment]
Alright. Can you install version 1.2.2 (you can find out the APK at the Releases tab of this repository) and try again?

**Comment by esetleges** [comment]
Hi there,

I am in same problem as Scizor. We are on same "Globe" network in Philippines.

I've tried Pixel IMS v1.2.2, 1.2.3, 1.2.4 and none of them worked. May the solution is that we need to change the "User Agent Section" in Pixel IMS since Globe has a SUPPORTED DEVICES list.

HERE is the link:
https://www.globe.com.ph/volte.html#gref
Click on "View Volte Devices" button to get the complete list.
<img width="889" alt="Screenshot 2023-04-17 at 20 59 51" src="https://user-images.githubusercontent.com/6225874/232493258-37d75503-7011-4e23-81f2-43531ca89f6d.png">

Question is how I can generate the requried format of any of those listed devices?

Lg U+ profile is not working (which is actually a Pixel 6a = GB17L)

**Comment by Truongtxvnp** [comment]
I have same Problem with my phone ( Pixel 5) in Viet Nam... In Phone seeting can enable VoLTE but it nos register IMS---> VoLTE not worrking( All voice calls are CSFB to 3G)

**Comment by grzywacz8** [comment]
I have the same problem (Poland).  After the tutorial shizuku was active, pixel ims had active options but volte and wificall didn't work.  after restarting the phone, shizuku stop (attachment) and pixel ims has inactive options despite granting permissions to shizuku.  (I'm attaching screenshots). I try ver. 1.2.2 and 1.2.4 and everytime is the same. What i doing wrong?
![Screenshot_20230527-103333](https://github.com/kyujin-cho/pixel-volte-patch/assets/50321833/bfa3b4ab-acd4-486b-84e3-e6afee319df0)
![Screenshot_20230527-103252](https://github.com/kyujin-cho/pixel-volte-patch/assets/50321833/3e33476f-3da8-4ecf-a272-01772936647d)

**Comment by kyujin-cho** [comment]
@grzywacz8 I'm incapable of Polish but from what I see it seems that the Shizuku service is not running on your phone. If it is started you can see a check mark at the top of the screen.

**Comment by arsradu** [comment]
You don't need Shizuku running all the time. Only for the first setup, and after system updates. 

It's normal to show up like this after restart, unless you have root and Shizuku set to autostart. Still, this should not affect the Pixel IMS' functionality. 
So, get Shizuku running once, then enter Pixel IMS app, configure it as you like (in case you can't see your carrier options, just restart Pixel IMS app). Once everything's set up, test and see if it works.

Also, what's your Android version? Is it 14? If so, make sure to also add IMS APN to your settings. I've had issues with WiFi calling because of this. VoLTE was running fine though.

Below is an example of what those settings should be. I've highlighted the ones you need to change. Everything else you should stay the same.

![Screenshot_20230412-093451](https://user-images.githubusercontent.com/86431007/231383322-f40ccd8c-9425-4b0d-b384-55d1f78e08d6.png)
![Screenshot_20230412-093547](https://user-images.githubusercontent.com/86431007/231383348-581ec380-2811-463f-9d96-cc433f1833ca.png)
![Screenshot_20230412-094422](https://user-images.githubusercontent.com/86431007/231383366-e1076dbc-86db-4e37-a83e-7af33bd766ed.png)

**Comment by grzywacz8** [comment]
Thx for help. I change operator to other and now all works.

**Comment by kyujin-cho** [comment]
Looks like we can close this issue now. Please feel free to reopen issue if something changes.
