### ISSUE TITLE
Pixel6a version 1.2.2, 1.2.3, 1.2.4 not work on VodafoneHU carrier

### ISSUE THREAD

**Issue by Cainsoft** [kyujin-cho/pixel-volte-patch#127]
I tested the last 3 versions, but the IMS Status is always unregistered.

**Comment by Cainsoft** [comment]
Hi,
Android 13, build: TQ2A.230505.002.
Yes I tried, I created the IMS manually (Name:IMS, APN:IMS, APN type: IMS)  
I just installed the Pixel IMS app, I didn't use it before.
Thx

**Comment by arsradu** [comment]
Can you upload a screenshot of Shizuku? Is it running ok? Is the Pixel IMS app allowed for Shizuku? Options in Settings are enabled?

**Comment by Cainsoft** [comment]
![Screenshot_20230511-190125](https://github.com/kyujin-cho/pixel-volte-patch/assets/44017122/7225dd6d-893d-45c0-bdc7-daa418d3496b)
![Screenshot_20230511-190059](https://github.com/kyujin-cho/pixel-volte-patch/assets/44017122/0ba42941-ad6e-4a85-87e7-48f94da0c6fe)
![Screenshot_20230511-190019](https://github.com/kyujin-cho/pixel-volte-patch/assets/44017122/9aa2e190-a679-4ae0-91e2-7930e8082d93)
I followed the instructions and made the settings, I attach the screenshots.

**Comment by Cainsoft** [comment]
Hi,
When I make a call, the phone disconnects from 4G and switches to Edge/Gsm
network. Same for incoming calls.
I have also activated a new sim card, but VoLte does not work.

**Comment by Cainsoft** [comment]
Thx. It's night here :), I'll check with Vodafone customer service tomorrow.

arsradu ***@***.***> ezt írta (időpont: 2023. máj. 11., Cs
21:43):

**Comment by arsradu** [comment]
Unfortunately, I know how it is. :)) This is not the first time someone denies me access to a service, just because the SIM card is in an "unsupported" device. I just ask for the services to be turned on. Where do I use them, in which phone, it's my business. And of course it works!

I think soon we'll start to see official support for this device, as well. In Romania they already started with Android 13 QPR 3 Beta 2.1....if I'm not mistaken. But it's only VoLTE. For WiFi Calling, we still rely on Shizuku + IMS app. 

Still, it's a start. And a good start.

I'm on Android 14 PB2, and native support is there, as well, but only for VoLTE (probably 5G, as well, but I can't test that part).

So...I think it's just a matter of time until they will be officially supported, and you won't get any "we can't activate the service cause you don't have a compatible phone, or hasn't been bought from us" or some BS like that. :)

Fingers crossed! And I'm really glad you managed to get it working!

Enjoy! :)
