### ISSUE TITLE
[Feature request] Apply on boot setting

### ISSUE THREAD

**Issue by warmoans** [kyujin-cho/pixel-volte-patch#143]
An apply on boot setting would be very useful so I don't have to apply settings on every boot. This would obviously only work for those with root as Shizuku doesn't start on boot without root.

Another option would having the app convert all the applied settings into a magisk module so they were applied on boot.

**Comment by arsradu** [comment]
Hello,

You don't need to apply settings on every boot. And you don't need root either. The settings are kept until the next OS upgrade.

**Comment by arsradu** [comment]
I don't have root. I don't like root. :) So...Shizuku is not enabled on boot for me. But, as I said, it's not required for Shizuku to be enabled as root (and to start on system boot) in order for these settings to work. They should work fine without root.
Enhanced LTE icon should show up only if you have 2CA/3CA in your area, and if the phone is doing carrier aggregation. Otherwise, you will just see LTE/4G.

Can you try to uninstall and reinstall the app? I don't see any reason why it would work for me but not for other people. :))

**Comment by arsradu** [comment]
Yes, it's perfectly normal to look like that. :)

However, all the services and options that you previously set up when Shizuku was running, should still be working just fine.

The Pixel IMS app shows Shizuku is not running, because it's not running at that moment. That's perfectly normal. BUT that doesn't mean that the options that you set up don't work.

As I was saying, you need Shizuku running (with or without root, it doesn't matter) ONLY the first time you set up the Pixel IMS app, and after installing a new OS upgrade. The setting you made in the app are still enabled, even if Shizuku service is not running at that moment. It's NOT required for those options to work, it's only required for those options to be enabled. Once enabled, you don't need Shizuku anymore.

**Comment by warmoans** [comment]
Settings seem to be sticking now since reinstalling app.

**Comment by warmoans** [comment]
Sorry should have double checked, everything but "Hide Enhanced Data" is sticking to my preferred setting (disabled).

**Comment by arsradu** [comment]
So it should show the 4G+ icon but it still doesn't?

**Comment by arsradu** [comment]
I see... Well it works now! :) Could have been some caches or something. Never had any issues myself. That's why I was surprised when I read your message. But anyway, good thing that it works!
Enjoy!

**Comment by arsradu** [comment]
Which settings? All settings? I thought this has been solved. :))

I'm not sure which log you could take.... I'm guessing they are probably not really saved, if they show "unsaved" after a reboot. So...the check should be to see if they're really saved or not. But I don't know how you would do that unfortunately.

**Comment by warmoans** [comment]
It works because the effect of the settings are there. The specific settings are "Enable Enhanced 4G LTE (LTE+)" and "Hide Enhanced Data lcon".

It's an intermittent issue, as far as I can tell.

**Comment by arsradu** [comment]
And why do you think the setting is not applied? If you activate Shizuku and enter Pixel IMS app, aren't those settings enabled?

Also, are you sure there should be 4G+ in that area? I can confirm the Enable Function works fine (I tested it today). But this might be a carrier issue.

So, are you saying you're definitely in a 4G+ area and there is still a 4G+ icon being displayed in your case although it's set to be hidden?

**Comment by arsradu** [comment]
I'm just trying to understand if it's a real issue or not. Because, believe it or not, I do not have this issue. And probably nobody else. So...yeah, it's either not an issue (or it's caused by external factors, not related to the app's functionality), or it's a very specific issue.

By the way, if you want it to show 4G+ (and it does, it's working fine for me), then Hide Enhanced Data Icon should be OFF.

Anyway, I'm off. I wish you good luck solving this issue.

**Comment by warmoans** [comment]
That's why I opened up an issue, to get this resolved by someone capable of helping. You've contributed very little to conversation.

And obviously it needs to be turned to off to see it. The settings says Enable in the name.

**Comment by warmoans** [comment]
> So you’re seeing some sort of settings being reset every reboot but not all, right? I’ve never observed such behavior before your mention. Somewhat related to Carrier Services maybe? Anyway, saving and persisting the value is controlled solely by Android System and can’t be controlled on our side (the app).

Is some sort of apply on boot option not viable?

**Comment by mpoozd** [comment]
> So you’re seeing some sort of settings being reset every reboot but not all, right?

I encountered the same issue recently, voLTE didn't work so I had to apply the same steps to make it work again. 
It happened multiple times without even rebooting the phone. I'm on May update ( TQ2A.230505.002 )

**Comment by arsradu** [comment]
Clean install and no root + magisk and whatever patches you might have going on. This might solve your issues. The problem is not the app, it's the OS. The settings are already saved on boot. It's just the OS is doing something weird in that particular case. 
But what do I know? I'm just a nobody spamming github with my useless stupid questions. I'm not "competent" enough to even have an opinion. I don't even know why I'm doing this. It's not to help people, that's for sure. Cause that would be outrageous.
Anyway. Just my opinion. Treat it as you like. To me, this is not a bug. And there's no need for an extra feature to be developed since the app is already working as intended. Also, you can't fix a bug you can't replicate. Anyway, it's not the app that's doing something weird here. It's the phone. Clean install, remove root if you have it, and it will work perfectly fine. End of story.

**Comment by kyujin-cho** [comment]
> > So you’re seeing some sort of settings being reset every reboot but not all, right? I’ve never observed such behavior before your mention. Somewhat related to Carrier Services maybe? Anyway, saving and persisting the value is controlled solely by Android System and can’t be controlled on our side (the app).
> 
> Is some sort of apply on boot option not viable?

It is more correct to say "The application can't control such behavior". There is no such option to enable "persist after reboot". Whether to retain value or not is totally in control of android system.

**Comment by ghost** [comment]
If the 'Carrier Config' app is disabled or fails to retrieve values, the dial will work temporarily but will not save values on reboot.
The 'Carrier service' app is a Google app and is about RCS Chats, so it's not related to this issue.

ps. I had the same issue and was working on it, and I happened to notice it while cleaning out unnecessary apps from ADB.
