### ISSUE TITLE
Distribution via Play Store

### ISSUE THREAD

**Issue by alexfh** [kyujin-cho/pixel-volte-patch#186]
Allowing app installation from unverified sources has security implications and is not always desirable or even possible (e.g. on devices with enterprise policies). I wonder if it was feasible to publish the app to the Play Store? I suspect that would require quite a time investment, but that would allow more folks to use this awesomeness ;)

**Comment by arsradu** [comment]
Not sure Google would be very happy with this app. :)) After all, it kinda forces their hand to allow support for IMS services in countries that don't normally support them on the Pixel (the so-called "unsupported countries"). But since we're using this, I think it's obvious for everyone that the problem is not on the carrier side, but on the OS side.

**Comment by exolon** [comment]
That's what I thought too, but then again Network Guru also allows some similar stuff and it's on the store... But then again it's Google, you never know😟

**Comment by arsradu** [comment]
True... On the other hand, if Google starts doing it themselves (as it seems to be the case), would there even be a need for this app anymore?

**Comment by kyujin-cho** [comment]
Hey, thanks for reminding me about this issue. It was (and still is) definitely on the road map in my brain, but recently I did not have enough time to take a look about those thingies... But I'll do my best to make it done.

**Comment by kyujin-cho** [comment]
Update: I've just published app to the Play Store. Waiting for review. Now let's see what happens...

**Comment by kyujin-cho** [comment]
App available now on [Play Store](https://play.google.com/store/apps/details?id=dev.bluehouse.enablevolte).

**Comment by arsradu** [comment]
Thank you so much!

**Comment by D0735** [comment]
@kyujin-cho It's missing.

**Comment by kyujin-cho** [comment]
I'll take a look.

**Comment by D0735** [comment]
@kyujin-cho How is the situation?
Is it possible to redistribute via play store?

**Comment by kyujin-cho** [comment]
@D0735 So turned out the situation is rather more complex than just reuploading the app. Google Play urges me to disclose my "real" name (my GH handle is my real name so it won't matter tho), "actual" residential address and my phone number also. Until those anti-privacy thingies are sorted out public access to all the publishes won't work out. What a frustrating idea.

**Comment by kyujin-cho** [comment]
Please understand revealing such informations is not a sort of an instantly decisive action and just refer the GH releases page for now.

**Comment by D0735** [comment]
Waiting for news.

**Comment by arsradu** [comment]
> @D0735 So turned out the situation is rather more complex than just reuploading the app. Google Play urges me to disclose my "real" name (my GH handle is my real name so it won't matter tho), "actual" residential address and my phone number also. Until those anti-privacy thingies are sorted out public access to all the publishes won't work out. What a frustrating idea.

What the f…? Is this the norm for all apps on the Play Store? If so, just take it off their platform. It’s not worth it. You can still upload it here, right?
Personally, I don’t use it anymore since Google themselves added official support for my country. But it was (still is) a really wonderful piece of software when I needed the most. 
But I do agree with you on this. Specific American intrusive way of thinking. I wonder if people in the EU are getting the same treatment.
By the way, is this a new thing? Cause the app was on the Play Store for a while now. 
And although I find it more annoying than funny, you probably came accross this youtube video (https://youtube.com/shorts/sAkInjju3ww?si=3sjUX805j5Ue1r4P) . So…yeah, looks like the US and China specifically still have their issues. And regular, even non-Chinese people, have to suffer for it. Because reasons, I guess.

**Comment by Abastro** [comment]
How about uploading this on F-Droid? It is reliable repository for open source softwares.
