### ISSUE TITLE
older pixel support

### ISSUE THREAD

**Issue by pejotigrek** [kyujin-cho/pixel-volte-patch#60]
hello,
I think I probably know the answer [short: no] but I'd like to ask anyway ;)
is your solution strictly dependant on hardware/software in the newer pixels, or it would be possible to make it work at - behold: pixel 2xl?

we have quite a number of 2XLs working in the family without a real need to upgrade them, and due to heavy usage of banking apps and contact-less payments I am unable to root them [tried that, no "magisk hide" strategy worked so I've unrooted and came clean], and because of that I can't use any root-based method to turn on VoWIFI or VoLTE even if my carrier supports it [unfortunately it doesn't support the pixels ;(]

**Comment by NXij** [comment]
On Qualcomm Pixels, when running on an unsupported carrier you will be using the wildcard mbn (modem related carrierconfig files, Wildcard defines carriers that do not have their corresponding mbn files present) which does not have the required IMS nv items, this is in contrast to Pixel6/7 with Shannon modems where IMS nv items are present by default, even when running in Wildcard configuration. 

So whilst you can enable the toggle, it sadly wont do anything since the modem doesn't have the IMS stack available and there is no way to load them without root.

**Comment by pejotigrek** [comment]
understood, thank you for such detailed answer!
